version: '2'

services:

  app:
    #    image: dtb/lego-rest
    build: .
    depends_on:
      - mypostgres
    environment:
      - MQTT_HOST=tcp://techhubmosquitto.westeurope.azurecontainer.io
      - MQTT_PORT=1883
      - MQTT_USER=techhub
      - MQTT_PASS=dtbhub2019
    ports:
      - "8080:8080"
      - "3000:3000"
      - "5555:5555"

  mypostgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=demopass
      - POSTGRES_USER=demouser
      - POSTGRES_DB=mydb


