version: '2'

services:

  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mypostgres
    environment:
      - MQTT_HOST=tcp://mosquitto
      - MQTT_PORT=1883
      - MQTT_USER=demo
      - MQTT_PASS=demo
      - DB_USER=demouser
      - DB_PASS=demopass
      - DB_HOST=mypostgres
      - DB_NAME=mydb
      - DB_PORT=5432
    ports:
      - "8080:8080"
      - "3000:3000"
      - "5555:5555"

  mypostgres:
    image: timescale/timescaledb:latest-pg11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=demopass
      - POSTGRES_USER=demouser
      - POSTGRES_DB=mydb

  mosquitto:
    image: toke/mosquitto
    ports:
      - "1883:1883"


